### ISSUE TITLE
Left column navigation on /learn pages.

### ISSUE THREAD

**Issue by mattgreg** [ockam-network/website#307]
The expected behavior of the accordion nave pages in the learn section is:
When you click on a parent heading, the sub items should expand. If I then click on it again they should accordion closed again.

What happens. The only way to close a set of sub headings is to click another parent heading. 

This wasn't an issue when the document set was light, but with so many docs pages sometimes the accordion'd subsections require a scroll to get to another parent level section.

**Comment by miedziak** [comment]
@mattgreg under each item ( even if it has children items inside ) we have an article, so clicking on it will cause open this article. This could be confusing. My suggestion is to make this chevron icon clickable which will make the action we need ( collapse/expand ) WDYT ?

**Comment by mattgreg** [comment]
yes. that chevron icon action is perfect.

**Comment by miedziak** [comment]
@mattgreg merged to develop (#327)
