### ISSUE TITLE
Change 'router' product page ulr to`hub`

### ISSUE THREAD

**Issue by mattgreg** [ockam-network/website#316]
Change URL and menu pull down name from `Ockam Router` to `Ockam Hub`

https://www.ockam.io/product/router

**Comment by miedziak** [comment]
@mattgreg what about headers/text inside?

**Comment by mattgreg** [comment]
any of the rendered text on the page is easy for me to update. I'll update the page copy/text myself.

I started to do this myself and then got nervous that I'd break some link or reference by changing the page name, url, meta, etc.

**Comment by miedziak** [comment]
@mattgreg please continue changing copy on this one #322

**Comment by mattgreg** [comment]
changes merged.
