### ISSUE TITLE
404 from old CLA document 

### ISSUE THREAD

**Issue by Necromos** [ockam-network/website#335]
Old CLA document was available https://www.ockam.io/learn/guides/contributions/cla where the new one is under https://www.ockam.io/learn/how-to-guides/contributing/cla which leads to 404 for people who will use the CLA action implemented. I would suggest to go with a 30x redirect to fix it

**Comment by miedziak** [comment]
resolved in: #345

**Comment by miedziak** [comment]
CC @mattgreg
