### ISSUE TITLE
No CLA bot message appears when recheckcla typed

### ISSUE THREAD

**Issue by Necromos** [ockam-network/website#336]
It looks like the message is not being sent when `recheckcla` is typed. My assumption is that `PERSISTANCE_GITHUB_TOKEN` secret is not present OR token behind it was removed/changed somehow.

**Comment by Necromos** [comment]
recheckcla

**Comment by Necromos** [comment]
recheckcla

**Comment by mrinalwadhwa** [comment]
I've disabled the cla bot, it was buggy and did not offer a good experience for new contributors.
