### ISSUE TITLE
Update architecture diagrams

### ISSUE THREAD

**Issue by mattgreg** [ockam-network/website#353]
Update the following diagrams from the Miro design board, submit PR and merge to `develop`

<img width="875" alt="Screen Shot 2021-01-07 at 10 48 16 AM" src="https://user-images.githubusercontent.com/27310398/103932025-1c1fc680-50d6-11eb-9ed4-d29603c8cd72.png">

**Comment by miedziak** [comment]
Done, merged in #354 

Diagram from https://github.com/ockam-network/proposals/tree/main/design/0003-key-agreement-xx also merged there.
